### ISSUE TITLE
Add support for multiple instances with different FHIR server targets

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/mii-process-feasibility#55]
It should be possible to run the feasibility plugin on the same DSF instance multiple times with different configurations.

Specifically the plugin should support a configuration where:

1. the originating organization of a task is used to decide whether the instance of the plugin processes the task
2.  each instance of the plugin can have a different FHIR server or flare instance as execution target as well as different execution paths (FLARE vs CQL)

Further it should be discussed whether all config vars (e.g. obfuscation setting) have to be instance specific or not.

**Comment by juliangruendner** [comment]
@wetret : It would be good to get feedback from you regarding the DSF way of achieving multi-instance plugin execution in one DSF instance

**Comment by SchmitzDan** [comment]
When Aktin support is discontinued at the end of the year, local instances of the FDPG feasibility portal operating in the DMZ will only be able to communicate with FHIR servers in the DIC via DSF. So this functionality will be mandatory.

**Comment by juliangruendner** [comment]
@SchmitzDan  - can you give a quick feedback why the portal for internal use only cannot run inside the DIZ directly ? - in which case the directBroker would suffice

**Comment by SchmitzDan** [comment]
@juliangruendner  If the portal is used purely internally, it can of course be operated within the DIZ and directBroker can be used. In addition, however, there is the case that researchers who do not work directly at the clinic and therefore do not have access to the internal network should be able to perform feasibility queries. The central FDPG does not offer the possibility to limit queries to individual sites (and should not for data protection reasons). Therefore, for this use case, a local instance that can be reached from the outside is required.
The connection does not necessarily have to run via the DSF if there are alternatives (such as the Aktin client). With the end of Aktin support, however, some polling option is needed, or just this extension of the DSF process.

**Comment by juliangruendner** [comment]
@SchmitzDan  - note that this issue is finally being resolved through the support of additional contexts:
https://github.com/medizininformatik-initiative/mii-process-feasibility/issues/114

@SchmitzDan: This will be available to be used from 1st of June for sites which need this mulit-context
